baseURL = "http://127.0.0.1:1313/"
languageCode = "en-us"
title = "Política em Números"
theme = "tale"


[[menu.main]]
 name = "Início"
 url  = "/"
 weight = 0

[[menu.main]]
 name = "Sobre"
 url  = "sobre"
 weight = 5

[[menu.main]]
 name = "Blog"
 url  = "post/"
 weight = 10
