name = "Política em Números"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_robust/blob/master/LICENSE.md"
description = "Política detalhada, aplicada."
homepage = "https://github.com/dim0627/hugo_theme_robust"
tags = ["blog"]
features = ["responsive", "thumbnail", "grid", "syntax highlight", "structured data", "ogp", "twitter cards"]
min_version = 0.42.2

[author]
  name = "Daisuke Tsuji"
  homepage = "https://yet.unresolved.xyz/"
